### ISSUE TITLE
dial tcp: lookup api.cloudflare.com on 10.96.0.10:53: server misbehaving

### ISSUE THREAD

**Issue by urbaman** [containeroo/cloudflare-operator#121]
It seems cloudflare-operator can't access the outside internet.
Is there a way to debug and solve it?

Thank you very much.

**Comment by rxbn** [comment]
Hi @urbaman 

Thanks for opening an issue! It looks like you have DNS problems in your Kubernetes cluster. Can you test if the problem also occurs with other domains and pods?

**Comment by urbaman** [comment]
Hi,

I actually found out it is a DNS problem, probably due to a misconfiguration between cluster's and calico's IP CIDRs.

I'm trying to get it solved and I'll be back.

Thank you.

**Comment by urbaman** [comment]
Hi @rxbn 

Solved the calico-cluster CIDR problem, and so DNS started.

Problem: cloudflare-controller deleted all of my A records in all of my zones in cloudflare.
How to stop this behiviour?

Should I keep all of my A and CNAME records managed through cloudflare-operator?

Thanks.

**Comment by rxbn** [comment]
cloudflare-operator is designed to be the single source of truth for all your DNS records. You should therefore create DNSRecord objects for all your desired DNS entries. Please note that you can configure cloudflare-operator to only manage certain zones: https://docs.cf.containeroo.ch/core_concept/#account

**Comment by urbaman** [comment]
Ok that's very helpful, I completely missed it, thank you very much!

**Comment by rxbn** [comment]
Thank you for using cloudflare-operator!
