### ISSUE TITLE
emphasize that controller will nuke existing DNS records in a zone

### ISSUE THREAD

**Issue by Dmitry1987** [containeroo/cloudflare-operator#138]
Hi, thanks for working on this nice new operator for cloudflare!
I noticed this in the docs and realized I almost destroyed all our DNS zone? 😆 
```
cloudflare-operator will fetch in the given interval (spec.interval) all Cloudflare DNS records for each Zone object and deletes them on Cloudflare if they are not present in Kubernetes. The interval will be inherited from Account.spec.interval.
```
Does this mean what I think it is, if I will specify an existing zone which has many existing old records, instead of controlling only the *newly created* DNS records for the ingresses, it will actually wipe out all zone records, and this is not stated in bold < h1> tags on the docs homepage?  (it should be 😅)  lol I have a feeling I just avoided a disaster, some 6th sense made me re-read all docs before enabling it on a cluster, and I wanted it to manage new records in an existing zone (staging one of course, but nevertheless it would make me very sad to lose the other 200 records in there of all staging services 🙈 ).

Is there a way to make it control only records under a specific DNS name level, and not touch the top level records?  Like to specify a "zone" as being `<my cluster name>.staging-domain.com` and it'll only manage records made at  `this-level.<my cluster name>.staging-domain.com` ?

great stuff in any case 🙏  but any risky or possibly destructive action like removal of all records in a zone, has to be emphasized as a warning in docs intro guide or somewhere else where it's very visible and obvious to any potential user 👍

**Comment by rxbn** [comment]
Hey @Dmitry1987 

Thanks for opening an issue :)

In short: Yes, cloudflare-operator will nuke all existing A, AAAA and CNAME records. You are absolutely right, this should be stated very clear in our documentation. I have already opened and internal ticket to implement this ASAP. It does however not touch any other record types (TXT, SRV, MX, ...). Though this could change in the future as cloudflare-operator is still in early beta.

Regarding your specific case: This is not possible and not intended as cloudflare-operator (and the Kubernetes API) should be the single source of truth for any DNS records in cloudflare. However, @gi8lino is currently working on a script that will fetch all your cloudflare DNS records and create Kubernetes objects for them.

I hope this fits your case as well.

Many thanks for your compliments!

-- Robin

**Comment by Dmitry1987** [comment]
thanks @rxbn , a script to import all existing records and create resources seems like a good solution, I agree. But it only works for a single cluster scenario, one cluster only, per DNS zone.  It means if we make a zone (subdomain) per cluster name, that would work, so I assume you are right in terms of best practices for newly created projects, but this workflow won't fit existing infra and projects who are migrating parts of their services to k8s and want to use the same zone (for example their customers already bookmarked their single-tenant domain names `something.slack.com` or `something.mysaas.com` and infra teams must keep using same zone and TLD, but migrate workloads one after another to k8s infra from vmware or something like that). 

I believe it's worth flagging the "wipe all and dominate" as an option, to be enabled or disabled, for user of the operator to decide if the cluster should manage all records from scratch, or coexist with existing DNS records (by default overwriting them on name collision for example, but that leaves a chance for correct configuration to co-exist in the same zone with legacy infra).

**Comment by rxbn** [comment]
Hi @Dmitry1987 Sorry for the delay.

Unfortunately, this is out of scope for cloudflare-operator, since it is designed to be de single source of truth for DNS records in your Cloudflare account (or single zones).

Thanks a lot for your suggestions, though.

Thanks for your understanding.

-- Robin
